// API
const API_URL = process.env.REACT_APP_BASE_API;
const PROFILES = process.env.REACT_APP_PROFILES;
const EXPERIENCES = process.env.REACT_APP_EXPERIENCES;
const USERNAME = process.env.REACT_APP_USERNAME;
const POSTS = process.env.REACT_APP_POSTS;

export { API_URL, PROFILES, EXPERIENCES, USERNAME, POSTS };
